// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKciJ2zCfq21G8wxiIS-GjGDM0JnuNvA0',
    appId: '1:360919281227:web:f3bb1e56f66fda2c5c27ce',
    messagingSenderId: '360919281227',
    projectId: 'mine-to-do',
    authDomain: 'mine-to-do.firebaseapp.com',
    storageBucket: 'mine-to-do.appspot.com',
    measurementId: 'G-D7002C4PXM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbMWlMncvdNne49KGgZD0e24TYtrEphnw',
    appId: '1:360919281227:android:1799110853bdb4285c27ce',
    messagingSenderId: '360919281227',
    projectId: 'mine-to-do',
    storageBucket: 'mine-to-do.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqRZQgPyfWDyUsDaU4dzW5zTGehPenejw',
    appId: '1:360919281227:ios:84fc72bd871db2455c27ce',
    messagingSenderId: '360919281227',
    projectId: 'mine-to-do',
    storageBucket: 'mine-to-do.appspot.com',
    iosClientId: '360919281227-akei5kuvaso09due70o2k0u4bs46e661.apps.googleusercontent.com',
    iosBundleId: 'com.example.dataEstructureDart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBqRZQgPyfWDyUsDaU4dzW5zTGehPenejw',
    appId: '1:360919281227:ios:84fc72bd871db2455c27ce',
    messagingSenderId: '360919281227',
    projectId: 'mine-to-do',
    storageBucket: 'mine-to-do.appspot.com',
    iosClientId: '360919281227-akei5kuvaso09due70o2k0u4bs46e661.apps.googleusercontent.com',
    iosBundleId: 'com.example.dataEstructureDart',
  );
}
